//templates
export const ADD_TEMPLATES = 'ADD_TEMPLATES';

export const FETCH_LATEST_TEMPLATES = 'FETCH_LATEST_TEMPLATES';
export const FETCH_LATEST_TEMPLATES_START = 'FETCH_LATEST_TEMPLATES_START';
export const FETCH_LATEST_TEMPLATES_SUCCESS = 'FETCH_LATEST_TEMPLATES_SUCCESS';
export const FETCH_LATEST_TEMPLATES_FAIL = 'FETCH_LATEST_TEMPLATES_FAIL';

//instances
export const ADD_INSTANCES = 'ADD_INSTANCES';

export const FETCH_LATEST_INSTANCES = 'FETCH_LATEST_INSTANCES';
export const FETCH_LATEST_INSTANCES_START = 'FETCH_LATEST_INSTANCES_START';
export const FETCH_LATEST_INSTANCES_SUCCESS = 'FETCH_LATEST_INSTANCES_SUCCESS';
export const FETCH_LATEST_INSTANCES_FAIL = 'FETCH_LATEST_INSTANCES_FAIL';